tig tmux popup prompt util to create a new sessions and change background color

diff --git a/tmux_popup_wrapper b/tmux_popup_wrapper
--- a/tmux_popup_wrapper
+++ b/tmux_popup_wrapper
@@ -5,5 +5,11 @@ if [[ $# -lt 1 ]] ; then
     exit 22
 fi
 
-tmux popup -d '#{pane_current_path}' -KER "bash_ask $*"
+if [[ -n "$TMUX_PANE" ]] ; then
+    #tmux popup -d '#{pane_current_path}' -KER "bash_ask $*"
+    tmux popup -d '#{pane_current_path}' -KER "tmux new -s popup \"printf \\\"\033]11;rgb:30/30/30\007\\\" ; bash_ask $*\""
+else
+    echo "Error: TMUX not running ..."
+    exit 22
+fi
 
